const supabase=window.supabase.createClient("https://sefuulovdserechlxncb.supabase.co","sb_publishable_o8YYHkc9w4NzqBvJv8FjkQ_8FXaKGfm"),bucket="birthday-media",q=s=>document.querySelector(s);let media=[];
const url=p=>supabase.storage.from(bucket).getPublicUrl(p).data.publicUrl;const status=t=>q("#status").textContent=t;
async function refresh(){const r=await supabase.from("birthday_media").select("*").order("display_order").order("created_at");if(r.error)return status(r.error.message);media=r.data||[];const photos=media.filter(x=>x.type==="photo"),c=media.find(x=>x.type==="collage"),m=media.find(x=>x.type==="music");q("#photoList").innerHTML=photos.map(p=>`<div><img src="${url(p.file_path)}"><button class="remove" data-id="${p.id}" data-path="${p.file_path}">×</button></div>`).join("")||"<p class='muted'>No photos yet.</p>";q("#collagePreview").innerHTML=c?`<img src="${url(c.file_path)}">`:"<p class='muted'>No collage yet.</p>";q("#musicPreview").innerHTML=m?`<audio controls src="${url(m.file_path)}"></audio>`:"<p class='muted'>No music yet.</p>"}
async function upload(file,type){const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"_"),path=type+"/"+Date.now()+"-"+crypto.randomUUID()+"-"+safe;let r=await supabase.storage.from(bucket).upload(path,file,{contentType:file.type});if(r.error)throw r.error;r=await supabase.from("birthday_media").insert({type,file_path:path,file_name:file.name,display_order:Date.now()});if(r.error){await supabase.storage.from(bucket).remove([path]);throw r.error}}
async function removeItem(id,path){let r=await supabase.from("birthday_media").delete().eq("id",id);if(r.error)throw r.error;await supabase.storage.from(bucket).remove([path])}
q("#loginForm").onsubmit=async e=>{e.preventDefault();q("#loginMsg").textContent="Signing in...";const r=await supabase.auth.signInWithPassword({email:q("#email").value,password:q("#password").value});if(r.error)q("#loginMsg").textContent=r.error.message;else{q("#loginCard").classList.add("hidden");q("#panel").classList.remove("hidden");refresh()}};
q("#logout").onclick=async()=>{await supabase.auth.signOut();location.reload()};
q("#uploadPhotos").onclick=async()=>{const fs=[...q("#photoInput").files];if(!fs.length)return status("Choose photos first.");try{status("Uploading...");for(const f of fs)await upload(f,"photo");q("#photoInput").value="";status("Photos uploaded ❤️");refresh()}catch(e){status(e.message)}};
q("#uploadCollage").onclick=async()=>{const f=q("#collageInput").files[0];if(!f)return status("Choose a collage first.");try{const old=media.find(x=>x.type==="collage");if(old)await removeItem(old.id,old.file_path);await upload(f,"collage");q("#collageInput").value="";status("Collage updated ❤️");refresh()}catch(e){status(e.message)}};
q("#uploadMusic").onclick=async()=>{const f=q("#musicInput").files[0];if(!f)return status("Choose audio first.");try{const old=media.find(x=>x.type==="music");if(old)await removeItem(old.id,old.file_path);await upload(f,"music");q("#musicInput").value="";status("Music updated ❤️");refresh()}catch(e){status(e.message)}};
q("#photoList").onclick=async e=>{const b=e.target.closest(".remove");if(!b)return;if(!confirm("Remove this photo?"))return;try{await removeItem(b.dataset.id,b.dataset.path);status("Photo removed.");refresh()}catch(x){status(x.message)}};
(async()=>{const r=await supabase.auth.getSession();if(r.data.session){q("#loginCard").classList.add("hidden");q("#panel").classList.remove("hidden");refresh()}})();